// scripts/platform/sonuclar/pano-duzeni.mjs için tip bildirimi.
export type KartDonemi = { hizli: string } | { baslangic: string; bitis: string };
export type IzgaraKonumu = { x: number; y: number; w: number; h: number };
export type PanoKarti = { id: string; tur: string; ayar?: Record<string, any>; donem?: KartDonemi; parametreDegerleri?: Record<string, string> } & IzgaraKonumu;
export declare const DONEM_SECIMLERI: ReadonlyArray<readonly [string, string]>;
export declare const VARSAYILAN_DONEM: Readonly<{ hizli: string }>;
export declare function donemTemizle(v: unknown): KartDonemi | null;
export declare function donemAraligi(donem: unknown, simdi?: Date): { baslangic: Date; bitis: Date };
export declare function donemMetni(donem: unknown): string;
export declare function sqlDonemParametreleri(sorgu: unknown): { baslangic: boolean; bitis: boolean };
export declare function sorgudaParametreVar(sorgu: unknown, ad: string): boolean;
export declare const EN_COK_KART_PARAMETRESI: number;
export declare const EN_COK_PARAMETRE_SECENEGI: number;
export declare function kartParametreDegeri(kart: { ayar?: any; parametreDegerleri?: Record<string, string> }, ad: string): string | null;
export declare function kartParametreleri(kart: { ayar?: any; parametreDegerleri?: Record<string, string> }): Record<string, string>;
export declare function kartParametrele<D extends { kartlar: PanoKarti[] }>(duzen: D, id: string, ad: string, deger: unknown): D;
export declare function kartDonemliMi(kart: { tur: string; ayar?: any }): boolean;
export declare function kartDonemle<D extends { kartlar: PanoKarti[] }>(duzen: D, id: string, donem: unknown): D;
export type PanoDuzeni = { surum: number; kartlar: PanoKarti[]; baslik?: string; aciklama?: string; ortamId?: string; otomatikYenileDk?: number };
export declare const IZGARA_SUTUN: number;
export declare const SATIR_BIRIMI: number;
export declare const IZGARA_BOSLUK: number;
export declare const EN_COK_YUKSEKLIK: number;
export declare const EN_COK_SATIR: number;
export declare function satirPikseli(h: number): number;
export declare function enKucukBoyut(kart: { tur: string; ayar?: any }): { w: number; h: number };
export declare function varsayilanBoyut(kart: { tur: string; ayar?: any }): { w: number; h: number };
export declare function cakisiyorMu(a: IzgaraKonumu, b: IzgaraKonumu): boolean;
export declare function okumaSirasinaDiz<K extends { x: number; y: number; id: string }>(kartlar: ReadonlyArray<K>): K[];
export declare function altSinir(kartlar: ReadonlyArray<{ y: number; h: number }>): number;
export declare function eskiDuzenGocu<K extends { id: string; tur: string; ayar?: any }>(liste: ReadonlyArray<{ kart: K; boyut?: unknown; yukseklik?: unknown }>, esit: boolean, ustY?: number): Array<K & IzgaraKonumu>;
export declare function eskiBicimMi(ham: unknown): boolean;
export declare function gorunurYerlesim<K extends { id: string; y: number; h: number }>(kartlar: ReadonlyArray<K>, gizli: ReadonlySet<string>): K[];
export declare function kartYerlestir<D extends { kartlar: PanoKarti[] }>(duzen: D, id: string, istek: Partial<IzgaraKonumu>): D;
export declare function kartSiraTasi<D extends { kartlar: PanoKarti[] }>(duzen: D, id: string, yon: 'yukari' | 'asagi'): D;
export type SablonParametresi = { ad: string; etiket: string; tur: 'hedef' | 'sayi' | 'secim'; en?: number; enCok?: number; varsayilan?: string | number; secenekler?: ReadonlyArray<readonly [string, string]> };
export type VeriSablonu = { anahtar: string; ad: string; aciklama: string; gorunum: 'sayi' | 'liste'; donemli: boolean; parametreler: ReadonlyArray<SablonParametresi> };

export declare const PANO_SURUMU: number;
export declare const EN_COK_KART: number;
export declare const KIMLIK_DESENI: RegExp;
export declare const YERLESIK_KARTLAR: ReadonlyArray<{ tur: string; ad: string; aciklama: string; w: number; h: number; en: { w: number; h: number }; varsayilan: boolean; donemli: boolean }>;
export declare const OZEL_KART_TURLERI: ReadonlyArray<{ tur: string; ad: string; aciklama: string }>;
export declare const SQL_GORUNUMLERI: ReadonlyArray<{ anahtar: string; ad: string }>;
export declare const ESIK_ISLECLERI: ReadonlyArray<string>;
export declare const ESIK_RENKLERI: ReadonlyArray<{ anahtar: string; ad: string }>;
export declare const EN_COK_ESIK: number;
export declare const EN_COK_SUTUN: number;
export declare const SQL_EN_UZUN: number;
export declare const SQL_ZAMAN_ASIMI_SN: Readonly<{ varsayilan: number; en: number; enCok: number }>;
export declare function sqlZamanAsimiTemizle(v: unknown): number | undefined;
export declare const NOT_EN_UZUN: number;
export declare const EN_COK_BAGLANTI: number;
export declare const VERI_SABLONLARI: ReadonlyArray<VeriSablonu>;
export declare const IC_SAYFALAR: ReadonlyArray<readonly [string, string]>;
export declare class PanoHatasi extends Error {}
export declare function iciAdresMi(adres: unknown): boolean;
export declare function turAdi(tur: string): string;
export declare function kartAdi(kart: { tur: string; ayar?: { baslik?: string } }): string;
export declare function yerlesikMi(tur: string): boolean;
export declare function varsayilanDuzen(): PanoDuzeni;
export declare function varsayilanMi(duzen: { kartlar: ReadonlyArray<PanoKarti> }): boolean;
export declare function sablonParametreleri(anahtar: string, ham: unknown): Record<string, string | number>;
export declare function kartTemizle(ham: unknown): Omit<PanoKarti, keyof IzgaraKonumu> & Partial<IzgaraKonumu>;
export declare function duzenTemizle(ham: unknown): PanoDuzeni;
export declare function kartKaldir<D extends { kartlar: PanoKarti[] }>(duzen: D, id: string): D;
export declare function kartEkle<D extends { kartlar: PanoKarti[] }>(duzen: D, kart: { id?: string; tur: string; ayar?: unknown; donem?: unknown; w?: number; h?: number }, konum?: { x: number; y: number }): D;
export declare function kartAyarla<D extends { kartlar: PanoKarti[] }>(duzen: D, id: string, ayar: unknown): D;
export declare function eksikYerlesikler(duzen: { kartlar: PanoKarti[] }): ReadonlyArray<{ tur: string; ad: string; aciklama: string; w: number; h: number; varsayilan: boolean }>;
export declare function esikRengi(deger: number, esikler: ReadonlyArray<{ islec: string; deger: number; renk: string }>): string | null;
export declare function sayiyaCevir(v: unknown): number | null;
export declare const SUTUN_GENISLIGI: Readonly<{ en: number; enCok: number }>;
export declare function gorunenSutunlar(ayar: ReadonlyArray<string>, sutunlar: ReadonlyArray<string>): string[];
export declare function sutunTasi(gorunen: ReadonlyArray<string>, ad: string, hedef: 'sol' | 'sag' | number): string[];
export declare function sutunGorunurlugu(gorunen: ReadonlyArray<string>, tum: ReadonlyArray<string>, ad: string, goster: boolean): string[];
export declare function sutunTuru(satirlar: ReadonlyArray<ReadonlyArray<unknown>>, i: number): 'sayi' | 'tarih' | 'metin';
export declare function satirlariSirala(satirlar: ReadonlyArray<ReadonlyArray<unknown>>, i: number, yon: 'artan' | 'azalan' | null): unknown[][];
export type PanoBicimi = { ondalik: 'oto' | number; onEk: string; sonEk: string; tarih: string; oran: string; hedef: number | null; gosterge: string };
export declare const VARSAYILAN_BICIM: Readonly<PanoBicimi>;
export declare const ONDALIK_SECENEKLERI: ReadonlyArray<'oto' | number>;
export declare const TARIH_BICIMLERI: ReadonlyArray<readonly [string, string]>;
export declare const ORAN_SECENEKLERI: ReadonlyArray<readonly [string, string]>;
export declare const GOSTERGE_SECENEKLERI: ReadonlyArray<readonly [string, string]>;
export declare const EN_COK_DILIM: number;
export declare const LISTE_EN_COK: number;
export declare function bicimTemizle(ham: unknown): PanoBicimi;
export declare function sayiBicimle(n: number, bicim?: unknown): string;
export declare function yuzdeDegeri(n: number, bicim?: unknown): number;
export declare function yuzdeBicimle(n: number, bicim?: unknown): string;
export declare function tarihBicimle(v: unknown, tarih: string): string | null;
export declare function hucreBicimle(v: unknown, bicim?: unknown): string;
export declare function degisimHesapla(simdi: number, onceki: number | null | undefined): { fark: number; yuzde: number | null; yon: 'artis' | 'azalis' | 'ayni' } | null;
export declare function pastaDilimleri(noktalar: ReadonlyArray<{ etiket: string; deger: number }>, enCok?: number): Array<{ etiket: string; deger: number; yuzde: number; diger: boolean }>;
export type SutunBicimi = { sutun: string; tur: 'rozet' | 'renk' | 'degisim' | 'sayac' | 'altSatir'; kurallar?: Array<{ deger: string; renk: string }>;
  esikler?: Array<{ islec: string; deger: number; renk: string }>; artisIyi?: boolean; altSutun?: string };
export declare const SUTUN_BICIM_TURLERI: ReadonlyArray<{ anahtar: string; ad: string }>;
export declare const ROZET_RENKLERI: ReadonlyArray<{ anahtar: string; ad: string }>;
export declare const EN_COK_SUTUN_BICIMI: number;
export declare const EN_COK_ROZET_KURALI: number;
export declare function renkAnahtari(v: unknown): string | null;
export declare function rozetKurallariniOku(metin: string): { kurallar: Array<{ deger: string; renk: string }>; hatalar: string[] };
export declare function esikleriOku(metin: string): { esikler: Array<{ islec: string; deger: number; renk: string }>; hatalar: string[] };
export declare function hucreSunumu(bicim: SutunBicimi | null | undefined, v: unknown, sayiBicimi?: unknown, altDeger?: unknown):
  null | { tur: 'rozet' | 'renk' | 'altSatir' | 'soluk'; metin: string; renk?: string | null; ok?: '▲' | '▼' | '='; alt?: string };
export declare const KART_SIMGELERI: ReadonlyArray<{ anahtar: string; ad: string }>;
export declare function ikinciDeger(ikinci: { tur: string; artisIyi?: boolean } | null | undefined, deger: number | null, diger: number | null):
  null | { tur: 'toplam'; oran: number } | { tur: 'karsilastir'; yuzde: number | null; fark: number; ok: '▲' | '▼' | '='; renk: string };
export declare const OTOMATIK_YENILEME_DK: ReadonlyArray<number>;
export declare function panoAyarla<D extends { kartlar: PanoKarti[] }>(duzen: D, ayar: { baslik?: unknown; aciklama?: unknown; ortamId?: unknown; otomatikYenileDk?: unknown }): D;
export declare function etkinHedef(kart: { ayar?: any }, duzen: { ortamId?: string }): { veritabaniId?: string; ortamId?: string; baglantiId?: string };
